services:
  database:
    image: mysql:8.2 # or mysql:8.2
    container_name: db_symrev
    ports:
      - "3306:3306"
    volumes:
      - dev_mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD

  php:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/www
    ports:
      - "0:9000"

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - .:/www
    ports:
      - "80:80"
    depends_on:
      - php

volumes:
  dev_mysql_data: